apiVersion: v1
kind: Service
metadata:
  name: {{ include "pysemdist.fullname" . }}
  labels: {{- include "pysemdist.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "pysemdist.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
